# Generated by Django 4.2.4 on 2023-08-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной странице'),
        ),
    ]
