# Generated by Django 4.2.4 on 2023-09-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ароматизированные', 'X1'), ('Ещё какие-то', 'X2')], default='Ароматизированные', max_length=30, verbose_name='Категория'),
        ),
    ]
