# Generated by Django 4.2.4 on 2023-09-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=100)),
                ('user_data', models.JSONField(default=dict)),
            ],
        ),
    ]
