# Generated by Django 4.2.4 on 2023-09-05 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_verification',
            field=models.BooleanField(default=False),
        ),
    ]
